# Generated by Django 3.0.3 on 2020-10-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_auto_20201025_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.CharField(max_length=300),
        ),
    ]
